### ISSUE TITLE
WiFi driver for PineTab 2

### ISSUE THREAD

**Issue by crabdancing** [nabam/nixos-rockchip#17]
Word is that the WiFi driver is [_kind_ of working upstream](https://www.reddit.com/r/PINE64official/comments/16z3ia8/comment/k3g8s5z/?utm_source=share&utm_medium=web2x&context=3), but it doesn't seem to be packaged here anywhere. Any plans to add it?

**Comment by nabam** [comment]
Sorry, I don't own PineTab myself, hardware support for PineTab was contributes by @asonix. I'm happy to accept contributions if you know how to solve it

**Comment by alxpettit** [comment]
If I ever have time, I might take a look upstream and make a PR tested against my personal hardware. :)

**Comment by tromshusky** [comment]
Whats up with pr #22? Will it get merged? It has wifi

**Comment by asonix** [comment]
I think "has WiFi" is a bit of an overstatement. The WiFi still doesn't work, but the driver can be loaded

**Comment by nabam** [comment]
Sorry folks, I didn't have much spare time maintain the repo recently. Builds has been failing for a while. I'll try to fix it this weekend and merge the PR.

**Comment by tromshusky** [comment]
https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+simplefb&type=commits
simplefb was changed around March23 this year, that might cause some failure

**Comment by tromshusky** [comment]
Got some Pietab2 image build successfully on my github
https://github.com/tromshusky/nixos-rockchip/releases/tag/v23.11.20240320.f091af0
Didn't test it

**Comment by nabam** [comment]
Fixed the pipeline, merged the PR. St least the driver should be available now.

**Comment by asonix** [comment]
There's also a dedicated wifi driver repo I've been thinking about getting packaged up as a kernel module but haven't gotten around to yet. It might improve the situation over the current in-tree driver: https://github.com/cringeops/bes2600

**Comment by tromshusky** [comment]
@asonix Did apply the dreemurrs patch like this:
 guess there is a way to include the patch directly from their repo but didnt care
```
  boot.kernelPackages = pkgs.linuxPackagesFor (pkgs.linux_6_9.override {
    argsOverride = rec {
      src = builtins.fetchurl {
            url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.2.tar.gz";
            sha256 = "0vz45ag1bkar9ir6w9bjiw05k7q2g1d5myb5n60dmf2k32n823cx";
      };
      version = "6.9.2";
      modDirVersion = "6.9.2-danctnix1";
      };
  });

  boot.kernelPatches = [{
    name = "v6.9.2-danctnix1";
    patch = builtins.fetchurl {
      url = "https://raw.githubusercontent.com/tromshusky/nixos-rockchip/frankenstein/mynix/v6.9.2-danctnix1.patch";
      sha256 = "1pg4cml49ymywsqfw0lasfakjx4a9p4wxl95cpd5mql2z9nar1m8";
    };
  }];
```
Boots kernel but goes into emergency shell.
```
[   20.114815] dw-mipi-dsi-rockchip fe060000.dsi: [drm:dw_mipi_dsi_rockchip_probe [rockchipdrm]] *ERROR* fai7
[   20.187278] dw-mipi-dsi-rockchip fe060000.dsi: [drm:dw_mipi_dsi_rockchip_probe [rockchipdrm]] *ERROR* fai7
```
But working on it now to include those modules from
nixpkgs: 
```
  boot.initrd.availableKernelModules =
  
# Rockchip
      "dw-hdmi"
      "dw-mipi-dsi"
      "rockchipdrm"
      "rockchip-rga"
      "phy-rockchip-pcie"
      "pcie-rockchip-host"
```
Renting an ARM vps to build caches

**Comment by luigi311** [comment]
Danct just released 6.9.5 and it has the latest bes2600 driver so we dont need to pull in the bes2600 repo and create a module out of it anymore. It should also be fine to set it to automatically load on startup now and is what arch is doing.

**Comment by crabdancing** [comment]
Woah. Wait a minute, the driver's actually usable?

**Comment by tromshusky** [comment]
> Woah. Wait a minute, the driver's actually usable?

if you manage to boot 6.8, modprobe bes2600 works
you have to apply it after screen timeout again.

if you want you can use the release that i linked

**Comment by crabdancing** [comment]
So you have to modprobe it again? Sounds like the sort of thing a script workaround could fix

**Comment by asonix** [comment]
6.9.6 has been merged with bes2900 auto-enabling on boot :)

**Comment by tromshusky** [comment]
big thank you!
allowed me to do my first successful ```nixos-install ...``` to emmc on this machine!
