### ISSUE TITLE
Add support for Orange Pi CM4 module

### ISSUE THREAD

**Issue by Kenzu** [nabam/nixos-rockchip#20]
Hi

Would love to get support for Orange Pi CM4 module. 
http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-CM4-1.html 
Looks like SOQUARTZ CM4, with same cpu.
Also the Orange Pi 3B is the same cpu and pinout as Orange Pi CM4, but different wifi chip.

Would like to help with test and donation board if needed.

Thanks for your work

Jesper

**Comment by nabam** [comment]
Hi! I built something using https://github.com/nabam/nixos-rockchip/pull/21 with `orangepi-3b-rk3566_defconfig` uBoot config mentioned here http://www.orangepi.org/orangepiwiki/index.php/Orange_Pi_CM4#Compile_u-boot. But I don't know if it is going to be compatible with your hardware as device tree layout for CM4 systems depends on the baseboard.

Check it out and tell me if it works

**Comment by nabam** [comment]
Image https://github.com/nabam/nixos-rockchip/releases/download/v23.11.20240314.878ef7d/orange-pi-cm4-nixos-sd-image-aarch64-linux.img.zst

**Comment by Kenzu** [comment]
Hi.

Thanks a lot. I’m a bit busy at the moment, but will try and do some testing next week.

Thanks

Jesper

**Comment by Kenzu** [comment]
Btw, would it be difficult to use the 5.10 rockchip kernel from armbian? It is the only kernel that works with my 7” 1024x600 lcd on opi cm4 and 3b.
