### ISSUE TITLE
Trying to build gives 'error: linux 6.9 was removed because it has reached its end of life upstream'

### ISSUE THREAD

**Issue by john-craig** [nabam/nixos-rockchip#29]
As stated in the title. Currently trying to build an image for the pinetab, but it appears linux 6.9 was removed. Any suggestions for fixes?

It appears that danctnix has a tag for the latest 6.12 kernel here: https://github.com/dreemurrs-embedded/linux-pinetab2/tree/v6.12.1-danctnix1.

I tried forking this repository and building using that, but was running into issues related to patches. Any suggestions or guidance would be appreciated.

**Comment by asonix** [comment]
should be fixed now
