### ISSUE TITLE
Coming GitHub Actions update to Ubuntu 24.04 will break CI

### ISSUE THREAD

**Issue by msgilligan** [nabam/nixos-rockchip#35]
I manually updated from `ubuntu-latest` to `ubuntu-24.04` and the build failed. I will make a DRAFT PR with this change and link it to this issue for reference.

The failure I'm seeing in `check.yml` is that `qemu-efi` is trying to be installed and is not found:

```
Package qemu-efi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qemu-efi' has no installation candidate
Error: Process completed with exit code 100.
```

PR #36 should demonstrate the failure.

See: https://github.com/actions/runner-images/issues/10636

**Comment by asonix** [comment]
seems like qemu-efi has split into packages per-achitecture. we likely want qemu-efi-aarch64

**Comment by msgilligan** [comment]
> seems like qemu-efi has split into packages per-achitecture. we likely want qemu-efi-aarch64

I will give that a try. (Or we could just switch to `ubuntu-22.04` until we figure it out.  That way our build doesn't get broken by surprise. The "rollout" starts tomorrow so we should do something soon.)
